from PyQt5 import QtCore, QtGui, QtWidgets
from logic import *


class Ui_GrafCreator(object):
    def setupUi(self, GrafCreator):
        GrafCreator.setObjectName("GrafCreator")
        GrafCreator.setWindowIcon(QtGui.QIcon("icons/icon.png"))
        GrafCreator.resize(1124, 819)
        GrafCreator.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(GrafCreator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        GrafCreator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GrafCreator)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setToolTipDuration(2)
        self.menubar.setDefaultUp(True)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menunew = QtWidgets.QMenu(self.menubar)
        self.menunew.setObjectName("menunew")
        self.menuopen = QtWidgets.QMenu(self.menubar)
        self.menuopen.setObjectName("menuopen")
        GrafCreator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GrafCreator)
        self.statusbar.setObjectName("statusbar")
        GrafCreator.setStatusBar(self.statusbar)
        mainMenu = self.menubar
        fileMenu = mainMenu.addMenu("File")
        colorMenu = mainMenu.addMenu("Color")
        vertexMenu = mainMenu.addMenu("Vertex")
        edgeMenu = mainMenu.addMenu("Edge")
        algoMenu = mainMenu.addMenu("Algorithms")

        saveAction = QtWidgets.QAction(QtGui.QIcon("icons/save.png"), "Save", self)
        saveAction.setShortcut("Ctrl+S")
        saveAction.triggered.connect(self.save)
        fileMenu.addAction(saveAction)
        clearAction = QtWidgets.QAction(QtGui.QIcon("icons/clear.png"), "Clear", self)
        clearAction.setShortcut("Ctrl+O")
        fileMenu.addAction(clearAction)
        clearAction.triggered.connect(self.clear)
        blackAction = QtWidgets.QAction(QtGui.QIcon("icons/black.png"), "Black", self)
        blackAction.setShortcut("Ctrl+1")
        colorMenu.addAction(blackAction)
        blackAction.triggered.connect(self.black)
        redAction = QtWidgets.QAction(QtGui.QIcon("icons/red.png"), "Red", self)
        redAction.setShortcut("Ctrl+2")
        colorMenu.addAction(redAction)
        redAction.triggered.connect(self.red)
        greenAction = QtWidgets.QAction(QtGui.QIcon("icons/green.png"), "Green", self)
        greenAction.setShortcut("Ctrl+3")
        colorMenu.addAction(greenAction)
        greenAction.triggered.connect(self.green)
        blueAction = QtWidgets.QAction(QtGui.QIcon("icons/blue.png"), "Blue", self)
        blueAction.setShortcut("Ctrl+4")
        colorMenu.addAction(blueAction)
        blueAction.triggered.connect(self.blue)
        diamAction = QtWidgets.QAction(QtGui.QIcon("icons/diameter.png"), "Diameter", self)
        diamAction.setShortcut("Ctrl+5")
        algoMenu.addAction(diamAction)
        # diamAction.triggered.connect(self.show_diameter())
        radAction = QtWidgets.QAction(QtGui.QIcon("icons/radius.png"), "Radius", self)
        diamAction.setShortcut("Ctrl+6")
        algoMenu.addAction(radAction)
        # radAction.triggered.connect(self.show_radius())

        self.retranslateUi(GrafCreator)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(GrafCreator)

        self.vertex = True
        self.color = QtCore.Qt.black
        self.selected = None
        self.graf = Graf(20)

    def retranslateUi(self, GrafCreator):
        _translate = QtCore.QCoreApplication.translate
        GrafCreator.setWindowTitle(_translate("GrafCreator", "GrafCreator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GrafCreator", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GrafCreator", "Tab 2"))
        self.menunew.setTitle(_translate("GrafCreator", "File"))
        self.menuopen.setTitle(_translate("GrafCreator", "Edit"))
        self.actionNew.setText(_translate("GrafCreator", "New"))
        self.actionOpen.setText(_translate("GrafCreator", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GrafCreator = QtWidgets.QMainWindow()
    ui = Ui_GrafCreator()
    ui.setupUi(GrafCreator)
    GrafCreator.show()
    sys.exit(app.exec_())

